### ISSUE TITLE
missing COPYING file from gameboy-spoof

### ISSUE THREAD

**Issue by TheBlueTroll** [pepijndevos/arduino-boy#1]
You appear to be missing the COPYING file from the gameboy-spoof, which as pointed out in it, is required when it is redistrbuted. 
See [here for original file](https://bitbucket.org/adanscotney/gameboy-spoof/raw/5f62f48b65c56db4bb6e19e7e532f4ef55b3ccce/COPYING) to be included.

**Comment by pepijndevos** [comment]
You are of course totally right.

**Comment by TheBlueTroll** [comment]
Also, u made it on to HACKADAY.com!, well done! ;]

**Comment by pepijndevos** [comment]
I know :) There is no other way people would complain about copyright on my hacks.

**Comment by TheBlueTroll** [comment]
well copyright is important, even if its about a hack
